### ISSUE TITLE
Consider adding a property for broadcast capabilities for point-multipoint flows

### ISSUE THREAD

**Issue by theri** [panrg/path-properties#48]
From Jake's review:

> 4.
> Would it be useful to include a path property that captures the value
> of broadcast capabilities for point-multipoint flows?
>
> Maybe something like this:
>
>      Replication Efficiency:  A point-multipoint flow can be transported
>         over paths with a variety of replication capabilities at
>         the different nodes and links along the path.  For example, an
>         RTP Translator (RFC 3550) that replicates packets to multiple
>         receivers by producing a separate packet for each destination
>         in software has a different level of efficiency than a multicast-
>         capable router or switch that uses hardware to replicate multicast
>         packets to multiple interfaces, which has a different level of
>         efficiency than sending multicast IP packets across a broadcast-capable
>         physical link, such as GPON or MIMO broadcast channels.

Thanks for the suggestion.

As the examples in the document are intended to focus on properties related to the use cases in Section 3, I'm wondering what's the primary use case for this property? I imagine it might be related to protocol selection, i.e., a node could select between different protocols based on the replication efficiency of the path.

Could this property also be captured by the "Service function" property, e.g., have the RTP Translator be a path element, and have its functionality be defined as a service function that it applies to particular flows?

Is there a specific definition for a certain level of replication efficiency, e.g., is it possible to capture it as a number with a unit?

**Comment by cyrill-k** [comment]
I added an example of point-to-multipoint replication efficiency to the "protocol feature available" property, but I'm not sure if it really fits there...

However, I'm also fine with not adding replication efficiency as it is a very specific property not tied to our presented use cases.

**Comment by theri** [comment]
Closing, as we closed the corresponding PR.
