### ISSUE TITLE
Define "endpoint"

### ISSUE THREAD

**Issue by theri** [panrg/path-properties#60]
The current draft does not define "endpoint", and at the [IETF 112 PANRG session](https://youtu.be/m9uA2XKlmeU?t=516), several people said that perhaps this definition should be added.

Many revisions ago, the document did use "endpoint" in its definitions ([example](https://datatracker.ietf.org/doc/draft-enghardt-panrg-path-properties/01/)), but it didn't define the term, and then we switched most of these to "host". 
Now, the term "endpoint" only appears in the Introduction, and two of these appearances are quotes from draft-irtf-panrg-questions.

Not sure what the right path forward here is.
In the IETF 112 discussion, it sounded like an endpoint could be defined as simply the first or last node on a path, which could be a host, some proxy, a tunnel endpoint, or any other kind of node. So maybe we can add this as a separate definition and be done. 
Or, we could change our "Host" definition to "Endpoint" and then say that host is a specific kind of endpoint. In that case, we'll also want to revisit our definitions using "host", maybe these should say "endpoint" instead. I can already see a few places where this might be the case.

**Comment by cyrill-k** [comment]
For me, the terms host and endpoint in this document are essentially synonymous, so I would be okay to change the term from host to endpoint.
I think the original problem with the term endpoint was that we didn't have a clear definition.
Using the abstract notion of a node and defining the endpoint as the first/last node of a path should cover all different types of endpoints, I think.

I think defining "endpoint" and keeping the definition of "host" throughout the document adds more confusion than it helps.
Also, looking through the document, I don't see any occurrence of host, where we cannot use endpoints instead.

Another possibility could be to define an endpoint in a more abstract way, e.g., "an endpoint is an entity that is the consumer of a data received from the network and originator of data sent to the network.". Then we could state that an endpoint is in control of the respective host and thus represents the actual source and destination.

What do you think about these two approaches?

**Comment by theri** [comment]
I think we should define endpoint as the first/last node of the path, and then substitute "host" throughput the document (and maybe say that an endpoint can be a host when we give examples).
I'll put in a PR.
