### ISSUE TITLE
Define "end-to-end"?

### ISSUE THREAD

**Issue by theri** [panrg/path-properties#61]
At the [IETF 112 PANRG session](https://youtu.be/m9uA2XKlmeU?t=516), Gorry suggested that maybe the path properties draft should define "end-to-end", a concept often talked about on the transport layer.

**Comment by cyrill-k** [comment]
If we decide to add a definition of endpoint in the document (#60), then we could naturally define end-to-end as the path consisting of the sending endpoint, a virtual path element connecting them, and the receiving endpoint.
An end-to-end path property would then be define over these three entities.

Also, I think we already have an example in the definition of a path that closely resembles what I would imagine is the definition of an end-to-end path to be:
> Similarly, the representation of a path and its
properties, as it is known to a specific entity, may be more
complex and include details about the physical layer technology,
or it may be more abstract and only consist of a specific source
and destination which is known to be reachable from that source.

**Comment by theri** [comment]
I like this idea!
I'll tackle this issue together with #60 (Define "endpoint").
