### ISSUE TITLE
Definitions depend on context

### ISSUE THREAD

**Issue by theri** [panrg/path-properties#62]
At the [IETF 112 PANRG session](https://youtu.be/m9uA2XKlmeU?t=516), Sabine Randriamasy brought up the point that a definition can be relative to different scopes, e.g., an endpoint can mean different things in routing VS transport, or for flows VS applications.

While Section 2.1 of the path properties draft already mentions that the terminology in the document is applicable to different technologies, maybe it should mention the different contexts as well. Or this could be part of the introduction.

Quoting from two emails by @cyrill-k:
> "My suggestion is to mention in the introduction that even for a single PAN technology, there might be different contexts (e.g., data- and control-plane) where the entities might have different behavior and properties."
> 
> "[…] maybe we could emphasize that even for a single PAN technology, different contexts, e.g., data- and control-plane, can use a different terminology in terms of nodes, links, and thus paths."

**Comment by cyrill-k** [comment]
I think it should be sufficient to add a few sentences to Section 2.1 to address the issue of contexts for specific technologies.
I would not put it in the introduction, since in my opinion it is not necessary to think about different contexts to understand the terminology.
