### ISSUE TITLE
Try to make path definition clearer/more readable

### ISSUE THREAD

**Issue by theri** [panrg/path-properties#70]
Via @SpencerDawkins in Last Call:

> In the definition of “Path”, 
>
> For multicast or broadcast, a packet may be sent by one node and received by multiple nodes. In this case, the packet is sent over multiple paths at once, one path for each combination of sending and receiving node; these paths do not have to be disjoint.
>
> I think the point this text is making is that if a sending node performs broadcast or multicast over multiple paths, that’s not relevant to the definition of a path in this document - each one of the paths from sender to receiver(s) is just another path, according to this definition. 
>
> Is that correct? If so, perhaps this could be a second paragraph on its own within the definition, to be clearer. 

Yes, I would say that this is correct.

In general, I think the Path definition is quite long and includes lots of aspects. I'll see what we can do to make it clearer.

**Comment by cyrill-k** [comment]
One easy fix could be to make the path definition minimal, i.e., "A sequence of adjacent path elements over which a packet can be transmitted, starting and ending with a node. A path is unidirectional.".
And then have the rest of the explanations in a separate paragraph below.

I think we can maybe rearrange some of the text to make the text clearer.
I can do a first pass for the rephrasing and make a PR.
