### ISSUE TITLE
Rephrase sentence in Transparency definition

### ISSUE THREAD

**Issue by theri** [panrg/path-properties#71]
Via @SpencerDawkins in Last Call:

> In the definition of “Transparency”, I found this sentence difficult to parse: 
>
> A can for example be blocking packets or reading and modifying (other protocol) headers or payloads.
>
> Perhaps
>
> For example, A can be blocking packets or reading and modifying (other protocol) headers or payloads.

**Comment by cyrill-k** [comment]
Sounds good to me :+1:
