### ISSUE TITLE
(Colin's Review): Clarification in Section 3.1

### ISSUE THREAD

**Issue by boucadair** [panrg/path-properties#79]
In Section 3.1, 
`“Entities may select their paths to fulfill a specific goal by specifying target properties for their selected paths” `

Is the intent that an entity will specify a target property and the network will select a path to fulfil that property, or that the entity will somehow measure the property and choose a path that meets it?

**Comment by cyrill-k** [comment]
I would say that both are examples for a use case related to path selection.
We wanted to express that target properties describe an entity's **intent** for which path properties are desirable for their paths.

In the last paragraph of Section 3.1, we discuss this point in more details: "Path selection can be done either by the communicating node(s) or by other entities within the network: A network (e.g., an AS) can adjust
its path selection for internal or external routing based on path properties. ..."

Maybe we can clarify the sentence in question to: "Entities can achieve a specific goal by specifying target properties for their paths. Such paths can be provided by the network or selected by the entity itself from all available paths."

**Comment by csperkins** [comment]
That rewording seems clearer.
