### ISSUE TITLE
(Colins' Review) service invocation examples

### ISSUE THREAD

**Issue by boucadair** [panrg/path-properties#81]
Systems such as Apple’s Private Relay, MASQUE, etc., have gained prominence while this draft was under development. Should such systems be considered as examples of service invocation, as in Section 3.3, or do they raise broader issues for path awareness by changing the trust model?

Med: This is an invitaion to discuss, not a request to make changes.

**Comment by theri** [comment]
I guess we don't have a fully fleshed out trust model in this document, so this seems a bit too complex for Section 3.3, which I see more as transport- and performance-related services, not security- or privacy-related ones.

However, I could see us mention these potential use cases in the Security Considerations section, which already talks about security-related properties and already mentions trust and VPNs.

**Comment by csperkins** [comment]
Makes sense. The draft doesn't need to have all the answers, but should highlight where there are questions and where the understanding is evolving.

**Comment by theri** [comment]
Addressed by #84
