### ISSUE TITLE
IRSG Review (Dave Oran): Perform no worse than the default case

### ISSUE THREAD

**Issue by theri** [panrg/path-properties#87]
From the IRSG review by Dave Oran:

> In 3.1 Path Selection you say “…a path selection algorithm should aim to not perform worse than the default case most of the time.” I’m not entirely sure what constitutes the “default case”. Is it the case where no path selection is made by the user, or where no path selection is possible? If the former, I can certainly imagine someone intentionally selecting a worse performing path for background traffic. Perhaps better wording would be “…a path selection algorithm should aim to do a better job of accommodating the user’s requirements than the default case of not selecting a path”.

**Comment by boucadair** [comment]
Good catch. I would personally reword to: 

   As a baseline, a path selection algorithm should aim to not perform
   worse than a random path selection most of the time.

**Comment by daveoran** [comment]
So, it's ok if it performs better but ignores or violates some other selection criterion the user asked for?

**Comment by theri** [comment]
I think clarifying the "default case of not selecting a path" is fine here. Basically, if you're adding a path selection logic, don't make the situation worse, with respect to the target properties (which can be network performace related or other related to other objectives such as security, which we already say in Section 3.1).

I'll do a PR.

**Comment by daveoran** [comment]
i don't want to quibble over wording, so what you say above is ok if you think the reader takes away the meaning of  "perform better" that you intend from section 3.1.
