### ISSUE TITLE
IRSG Review (Dave Oran): Symmetric paths

### ISSUE THREAD

**Issue by theri** [panrg/path-properties#90]
From the IRSG review by Dave Oran:

> In “Symmetric path” do all the elements need to be symmetric or only the nodes? Do we care about packets traversing LAGs or or other parallel connections between a pair of nodes constituting different paths? Just a question, really…

**Comment by theri** [comment]
According to our definition, this depends on the level of abstraction on which you consider the nodes:
> Two paths are symmetric if the path and its reverse path consist of the same path elements on the same level of abstraction, but in reverse order.

I imagine that if you care about the different parallel links, you'll model them as separate links, so the reverse path will not be symmetric if a packet traverses the other link.
If you don't care about the different parallel links, you'll model them as a single link.

Does that make sense?

**Comment by daveoran** [comment]
Yes. My question was provoked by some material elsewhere that talks about only nodes having interesting path properties.

**Comment by theri** [comment]
Was this material outside the draft at hand? Because I think links may very well have interesting path properties.

Do you believe that any text changes are needed?

**Comment by daveoran** [comment]
I also think links can have interesting path element properties, so explicitly stating that they don't in section 3.1 might come back to bite.

**Comment by theri** [comment]
Ah, so you *are* talking about text in this draft, in Section 3.1?
Or which exact text says that links cannot have interesting path properties? Because links definitely can have interesting path properties, and if that's not clear in the document, then I do want to change text.

**Comment by daveoran** [comment]
Sorry, the above comment about section 3.1 was basically wrong. As long as the notion, as you elucidate above, that "if you care about the different parallel links, you'll model them as separate links, so the reverse path will not be symmetric if a packet traverses the other link." comes out in the text.
