### ISSUE TITLE
IRSG Review (Dave Oran): Cached knowledge

### ISSUE THREAD

**Issue by theri** [panrg/path-properties#92]
From the IRSG review by Dave Oran:

> For “Transport Features available”, I wonder what to take away from the statement that the path property’s value is based on “cached knowledge”? Why not possibly policy, or by testing a path to see if it carries a given protocol before making it eligible for path selection?

**Comment by theri** [comment]
Right, yes, these could be based on policy or testing, too. I can add that.

**Comment by cyrill-k** [comment]
This looks good to me.
